/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dakonfix;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author amin
 */
public class dakonDisplay extends javax.swing.JFrame {

    private int pemainAcak;
    private int mulaiPlayerA1, mulaiPlayerA2, mulaiPlayerA3;

    private int sizePlayerA1, sizePlayerA2, sizePlayerA3,
            sizePlayerB1, sizePlayerB2, sizePlayerB3;

    private boolean statusPlayerA1, statusPlayerA2, statusPlayerA3, statusPlayerA4, statusPlayerA5, statusPlayerA6,
            statusPlayerB1, statusPlayerB2, statusPlayerB3, statusPlayerB4, statusPlayerB5, statusPlayerB6,
            statusScorelumbungA, statusScorelumbungB;

    int angka, kasus;
    boolean playerA;

    Timer time = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            int temp;
            System.out.println("case : " + kasus);
            if (kasus == 14) {
                kasus = 0;
            }
            if (kasus != 7) {

                tambahDakon(kasus + 1);
                angka--;
            }

            kasus++;
            if (angka == 0) {
                temp = ambilDakon(kasus);

                if (temp != 1) {
                    angka = temp;
                } else {
                    tembakDakon(kasus, playerA);
                    giliranPlayerB();
                }
            }
            if (angka < 1) {
                time.stop();
            }
        }

    });
    Timer time2 = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            int temp;
            if (kasus == 14) {
                kasus = 0;
            }
            if (kasus != 0) {
                System.out.println("angka :" + angka);

                tambahDakon(kasus + 1);
                angka--;
            }
            kasus++;
            if (angka == 0) {
                temp = ambilDakon(kasus);
                System.out.println("temporary : " + temp);
                System.out.println("case : " + kasus);
                if (temp != 1) {
                    angka = temp;
                } else {
                    tembakDakon(kasus, playerA);
                    giliranPlayerA();
                }
            }
            if (angka < 1) {
                time2.stop();
            }
        }

    });

    /**
     * Creates new form dakonDisplay
     */
    public dakonDisplay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        textPlayer = new javax.swing.JLabel();
        playerB1 = new javax.swing.JLabel();
        playerB2 = new javax.swing.JLabel();
        playerB3 = new javax.swing.JLabel();
        playerB4 = new javax.swing.JLabel();
        playerB5 = new javax.swing.JLabel();
        playerB6 = new javax.swing.JLabel();
        playerA1 = new javax.swing.JLabel();
        playerA2 = new javax.swing.JLabel();
        playerA3 = new javax.swing.JLabel();
        playerA4 = new javax.swing.JLabel();
        playerA5 = new javax.swing.JLabel();
        playerA6 = new javax.swing.JLabel();
        lumbungPlayerA = new javax.swing.JLabel();
        lumbungPlayerB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(textPlayer);
        textPlayer.setBounds(410, 310, 190, 70);

        playerB1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        playerB1.setForeground(new java.awt.Color(255, 255, 255));
        playerB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerB1.setText("6");
        playerB1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playerB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerB1MouseClicked(evt);
            }
        });
        getContentPane().add(playerB1);
        playerB1.setBounds(750, 40, 100, 90);

        playerB2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        playerB2.setForeground(new java.awt.Color(255, 255, 255));
        playerB2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerB2.setText("6");
        playerB2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playerB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerB2MouseClicked(evt);
            }
        });
        getContentPane().add(playerB2);
        playerB2.setBounds(640, 40, 100, 90);

        playerB3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        playerB3.setForeground(new java.awt.Color(255, 255, 255));
        playerB3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerB3.setText("6");
        playerB3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playerB3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerB3MouseClicked(evt);
            }
        });
        getContentPane().add(playerB3);
        playerB3.setBounds(530, 40, 100, 90);

        playerB4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        playerB4.setForeground(new java.awt.Color(255, 255, 255));
        playerB4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerB4.setText("6");
        playerB4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playerB4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerB4MouseClicked(evt);
            }
        });
        getContentPane().add(playerB4);
        playerB4.setBounds(410, 40, 100, 90);

        playerB5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        playerB5.setForeground(new java.awt.Color(255, 255, 255));
        playerB5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerB5.setText("6");
        playerB5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playerB5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerB5MouseClicked(evt);
            }
        });
        getContentPane().add(playerB5);
        playerB5.setBounds(300, 40, 100, 90);

        playerB6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        playerB6.setForeground(new java.awt.Color(255, 255, 255));
        playerB6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerB6.setText("6");
        playerB6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playerB6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerB6MouseClicked(evt);
            }
        });
        getContentPane().add(playerB6);
        playerB6.setBounds(190, 40, 100, 90);

        playerA1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        playerA1.setForeground(new java.awt.Color(255, 255, 255));
        playerA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerA1.setText("6");
        playerA1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playerA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerA1MouseClicked(evt);
            }
        });
        getContentPane().add(playerA1);
        playerA1.setBounds(190, 190, 100, 90);

        playerA2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        playerA2.setForeground(new java.awt.Color(255, 255, 255));
        playerA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerA2.setText("6");
        playerA2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playerA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerA2MouseClicked(evt);
            }
        });
        getContentPane().add(playerA2);
        playerA2.setBounds(300, 190, 100, 90);

        playerA3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        playerA3.setForeground(new java.awt.Color(255, 255, 255));
        playerA3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerA3.setText("6");
        playerA3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playerA3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerA3MouseClicked(evt);
            }
        });
        getContentPane().add(playerA3);
        playerA3.setBounds(410, 190, 100, 90);

        playerA4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        playerA4.setForeground(new java.awt.Color(255, 255, 255));
        playerA4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerA4.setText("6");
        playerA4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playerA4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerA4MouseClicked(evt);
            }
        });
        getContentPane().add(playerA4);
        playerA4.setBounds(530, 190, 100, 90);

        playerA5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        playerA5.setForeground(new java.awt.Color(255, 255, 255));
        playerA5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerA5.setText("6");
        playerA5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playerA5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerA5MouseClicked(evt);
            }
        });
        getContentPane().add(playerA5);
        playerA5.setBounds(640, 190, 100, 90);

        playerA6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        playerA6.setForeground(new java.awt.Color(255, 255, 255));
        playerA6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playerA6.setText("6");
        playerA6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playerA6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerA6MouseClicked(evt);
            }
        });
        getContentPane().add(playerA6);
        playerA6.setBounds(750, 190, 100, 90);

        lumbungPlayerA.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lumbungPlayerA.setForeground(new java.awt.Color(255, 255, 255));
        lumbungPlayerA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lumbungPlayerA.setText("0");
        lumbungPlayerA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lumbungPlayerA);
        lumbungPlayerA.setBounds(50, 80, 150, 150);

        lumbungPlayerB.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lumbungPlayerB.setForeground(new java.awt.Color(255, 255, 255));
        lumbungPlayerB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lumbungPlayerB.setText("0");
        lumbungPlayerB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lumbungPlayerB);
        lumbungPlayerB.setBounds(850, 80, 150, 160);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dakon.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 1006, 275);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setTrue() {
        statusPlayerA1 = true;
        statusPlayerA2 = true;
        statusPlayerA3 = true;
        statusPlayerA4 = true;
        statusPlayerA5 = true;
        statusPlayerA6 = true;

        statusPlayerB1 = true;
        statusPlayerB2 = true;
        statusPlayerB3 = true;
        statusPlayerB4 = true;
        statusPlayerB5 = true;
        statusPlayerB6 = true;

    }

    private void setDisable() {
        playerA1.setEnabled(false);
        playerA2.setEnabled(false);
        playerA3.setEnabled(false);
        playerA4.setEnabled(false);
        playerA5.setEnabled(false);
        playerA6.setEnabled(false);

        playerB1.setEnabled(false);
        playerB2.setEnabled(false);
        playerB3.setEnabled(false);
        playerB4.setEnabled(false);
        playerB5.setEnabled(false);
        playerB6.setEnabled(false);
    }

    private void giliranPlayerB() {

        if (Integer.parseInt(this.playerA1.getText()) == 0 && Integer.parseInt(this.playerA2.getText()) == 0 && Integer.parseInt(this.playerA3.getText()) == 0
                && Integer.parseInt(this.playerA4.getText()) == 0 && Integer.parseInt(this.playerA5.getText()) == 0 && Integer.parseInt(this.playerA6.getText()) == 0
                && Integer.parseInt(this.playerB1.getText()) == 0 && Integer.parseInt(this.playerB2.getText()) == 0 && Integer.parseInt(this.playerB3.getText()) == 0
                && Integer.parseInt(this.playerB4.getText()) == 0 && Integer.parseInt(this.playerB5.getText()) == 0 && Integer.parseInt(this.playerB6.getText()) == 0) {
            if (Integer.parseInt(this.lumbungPlayerA.getText()) < Integer.parseInt(this.lumbungPlayerB.getText())) {
                textPlayer.setText("Player B adalah pemenang!");
            }else if (Integer.parseInt(this.lumbungPlayerA.getText()) == Integer.parseInt(this.lumbungPlayerB.getText())) {
                textPlayer.setText("SERI!");
            }else {
                textPlayer.setText("Player A adalah PEMENANG!");
            }
            playerA1.setVisible(false);
            playerA2.setVisible(false);
            playerA3.setVisible(false);
            playerA4.setVisible(false);
            playerA5.setVisible(false);
            playerA6.setVisible(false);
            playerB1.setVisible(false);
            playerB2.setVisible(false);
            playerB3.setVisible(false);
            playerB4.setVisible(false);
            playerB5.setVisible(false);
            playerB6.setVisible(false);

        } else {
            playerA1.setVisible(false);
            playerA2.setVisible(false);
            playerA3.setVisible(false);
            playerA4.setVisible(false);
            playerA5.setVisible(false);
            playerA6.setVisible(false);
            playerB1.setVisible(true);
            playerB2.setVisible(true);
            playerB3.setVisible(true);
            playerB4.setVisible(true);
            playerB5.setVisible(true);
            playerB6.setVisible(true);

            if (Integer.parseInt(this.playerB1.getText()) == 0 && Integer.parseInt(this.playerB2.getText()) == 0 && Integer.parseInt(this.playerB3.getText()) == 0
                    && Integer.parseInt(this.playerB4.getText()) == 0 && Integer.parseInt(this.playerB5.getText()) == 0 && Integer.parseInt(this.playerB6.getText()) == 0) {
                giliranPlayerA();
            }
        }

    }

    private void giliranPlayerA() {

        if (Integer.parseInt(this.playerA1.getText()) == 0 && Integer.parseInt(this.playerA2.getText()) == 0 && Integer.parseInt(this.playerA3.getText()) == 0
                && Integer.parseInt(this.playerA4.getText()) == 0 && Integer.parseInt(this.playerA5.getText()) == 0 && Integer.parseInt(this.playerA6.getText()) == 0
                && Integer.parseInt(this.playerB1.getText()) == 0 && Integer.parseInt(this.playerB2.getText()) == 0 && Integer.parseInt(this.playerB3.getText()) == 0
                && Integer.parseInt(this.playerB4.getText()) == 0 && Integer.parseInt(this.playerB5.getText()) == 0 && Integer.parseInt(this.playerB6.getText()) == 0) {
            if (Integer.parseInt(this.lumbungPlayerA.getText()) < Integer.parseInt(this.lumbungPlayerB.getText())) {
                textPlayer.setText("Player B adalah pemenang!");
            }else if (Integer.parseInt(this.lumbungPlayerA.getText()) == Integer.parseInt(this.lumbungPlayerB.getText())) {
                textPlayer.setText("SERI!");
            } else {
                textPlayer.setText("Player A adalah pemenang!");
            }

            playerA1.setVisible(false);
            playerA2.setVisible(false);
            playerA3.setVisible(false);
            playerA4.setVisible(false);
            playerA5.setVisible(false);
            playerA6.setVisible(false);
            playerB1.setVisible(false);
            playerB2.setVisible(false);
            playerB3.setVisible(false);
            playerB4.setVisible(false);
            playerB5.setVisible(false);
            playerB6.setVisible(false);
        } else {
            playerB1.setVisible(false);
            playerB2.setVisible(false);
            playerB3.setVisible(false);
            playerB4.setVisible(false);
            playerB5.setVisible(false);
            playerB6.setVisible(false);
            playerA1.setVisible(true);
            playerA2.setVisible(true);
            playerA3.setVisible(true);
            playerA4.setVisible(true);
            playerA5.setVisible(true);
            playerA6.setVisible(true);
            if (Integer.parseInt(this.playerA1.getText()) == 0 && Integer.parseInt(this.playerA2.getText()) == 0 && Integer.parseInt(this.playerA3.getText()) == 0
                    && Integer.parseInt(this.playerA4.getText()) == 0 && Integer.parseInt(this.playerA5.getText()) == 0 && Integer.parseInt(this.playerA6.getText()) == 0) {
                giliranPlayerB();
            }
        }
    }

    private void run() {

        if (playerA) {
            time.start();

        } else {
            time2.start();
        }
    }

    private void toLumbungA(int angka) {
        int temp, total;
        temp = Integer.parseInt(this.lumbungPlayerA.getText());
        total = temp + angka;
        lumbungPlayerA.setText(Integer.toString(total));
    }

    private void toLumbungB(int angka) {
        int temp, total;
        temp = Integer.parseInt(this.lumbungPlayerB.getText());
        total = temp + angka;
        lumbungPlayerB.setText(Integer.toString(total));
    }

    private void tembakDakon(int kasus, boolean playerA) {
        int angka = 0;
        switch (kasus) {
            case 14:
                if (playerA) {
                    angka = Integer.parseInt(this.playerB6.getText());
                    toLumbungA(angka);
                    this.playerB6.setText("0");
                } else {
                }
                break;
            case 13:
                if (playerA) {
                    angka = Integer.parseInt(this.playerB5.getText());
                    toLumbungA(angka);
                    this.playerB5.setText("0");
                } else {
                }
                break;
            case 12:
                if (playerA) {
                    angka = Integer.parseInt(this.playerB4.getText());
                    toLumbungA(angka);
                    this.playerB4.setText("0");
                } else {
                }
                break;
            case 11:
                if (playerA) {
                    angka = Integer.parseInt(this.playerB3.getText());
                    toLumbungA(angka);
                    this.playerB3.setText("0");
                } else {
                }
                break;
            case 10:
                if (playerA) {
                    angka = Integer.parseInt(this.playerB2.getText());
                    toLumbungA(angka);
                    this.playerB2.setText("0");
                } else {
                }
                break;
            case 9:
                if (playerA) {
                    angka = Integer.parseInt(this.playerB1.getText());
                    toLumbungA(angka);
                    this.playerB1.setText("0");
                } else {
                }
                break;
            case 8:
                break;
            case 1:
                break;
            case 2:
                if (!playerA) {
                    angka = Integer.parseInt(this.playerA1.getText());
                    toLumbungB(angka);
                    this.playerA1.setText("0");
                } else {
                }
                break;
            case 3:
                if (!playerA) {
                    angka = Integer.parseInt(this.playerA2.getText());
                    toLumbungB(angka);
                    this.playerA2.setText("0");
                } else {
                }
                break;
            case 4:
                if (!playerA) {
                    angka = Integer.parseInt(this.playerA3.getText());
                    toLumbungB(angka);
                    this.playerA3.setText("0");
                } else {
                }
                break;
            case 5:
                if (!playerA) {
                    angka = Integer.parseInt(this.playerA4.getText());
                    toLumbungB(angka);
                    this.playerA4.setText("0");
                } else {
                }
                break;
            case 6:
                if (playerA) {
                    angka = Integer.parseInt(this.playerA5.getText());
                    toLumbungA(angka);
                    this.playerA5.setText("0");
                } else {
                }
                break;
            case 7:
                if (playerA) {
                    angka = Integer.parseInt(this.playerA6.getText());
                    toLumbungA(angka);
                    this.playerA6.setText("0");
                } else {
                }
                break;
        }
    }

    private int ambilDakon(int kasus) {
        int angka = 0;
        switch (kasus) {
            case 1:
                angka = 0;
                break;
            case 2:
                angka = Integer.parseInt(this.playerB6.getText());
                if (angka == 1) {
                    playerB6.setText("1");
                } else {
                    playerB6.setText("0");
                }
                break;
            case 3:
                angka = Integer.parseInt(this.playerB5.getText());
                if (angka == 1) {
                    playerB5.setText("1");
                } else {
                    playerB5.setText("0");
                }
                break;
            case 4:
                angka = Integer.parseInt(this.playerB4.getText());
                if (angka == 1) {
                    playerB4.setText("1");
                } else {
                    playerB4.setText("0");
                }
                break;
            case 5:
                angka = Integer.parseInt(this.playerB3.getText());
                if (angka == 1) {
                    playerB3.setText("1");
                } else {
                    playerB3.setText("0");
                }
                break;
            case 6:
                angka = Integer.parseInt(this.playerB2.getText());
                if (angka == 1) {
                    playerB2.setText("1");
                } else {
                    playerB2.setText("0");
                }
                break;
            case 7:
                angka = Integer.parseInt(this.playerB1.getText());
                if (angka == 1) {
                    playerB1.setText("1");
                } else {
                    playerB1.setText("0");
                }
                break;
            case 8:
                angka = 0;
                break;
            case 9:
                angka = Integer.parseInt(this.playerA6.getText());
                if (angka == 1) {
                    playerA6.setText("1");
                } else {
                    playerA6.setText("0");
                }
                break;
            case 10:
                angka = Integer.parseInt(this.playerA5.getText());
                if (angka == 1) {
                    playerA5.setText("1");
                } else {
                    playerA5.setText("0");
                }
                break;
            case 11:
                angka = Integer.parseInt(this.playerA4.getText());
                if (angka == 1) {
                    playerA4.setText("1");
                } else {
                    playerA4.setText("0");
                }
                break;
            case 12:
                angka = Integer.parseInt(this.playerA3.getText());
                if (angka == 1) {
                    playerA3.setText("1");
                } else {
                    playerA3.setText("0");
                }
                break;
            case 13:
                angka = Integer.parseInt(this.playerA2.getText());
                if (angka == 1) {
                    playerA2.setText("1");
                } else {
                    playerA2.setText("0");
                }
                break;
            case 14:
                angka = Integer.parseInt(this.playerA1.getText());
                if (angka == 1) {
                    playerA1.setText("1");
                } else {
                    playerA1.setText("0");
                }
                break;
        }
        return angka;
    }

    private void tambahDakon(int next) {
        int lumbungB, lumbungA, isiB6, isiB5, isiB4, isiB3, isiB2, isiB1, isiA6, isiA5, isiA4, isiA1, isiA2, isiA3;
        lumbungA = Integer.parseInt(lumbungPlayerA.getText());
        lumbungB = Integer.parseInt(lumbungPlayerB.getText());
        isiB6 = Integer.parseInt(playerB6.getText());
        isiB5 = Integer.parseInt(playerB5.getText());
        isiB4 = Integer.parseInt(playerB4.getText());
        isiB3 = Integer.parseInt(playerB3.getText());
        isiB2 = Integer.parseInt(playerB2.getText());
        isiB1 = Integer.parseInt(playerB1.getText());
        isiA6 = Integer.parseInt(playerA6.getText());
        isiA5 = Integer.parseInt(playerA5.getText());
        isiA4 = Integer.parseInt(playerA4.getText());
        isiA3 = Integer.parseInt(playerA3.getText());
        isiA2 = Integer.parseInt(playerA2.getText());
        isiA1 = Integer.parseInt(playerA1.getText());
        switch (next) {
            case 1:
                lumbungPlayerA.setText(Integer.toString(lumbungA + 1));

                if (Integer.parseInt(playerA1.getText()) == 0 && Integer.parseInt(playerA2.getText()) == 0 && Integer.parseInt(playerA3.getText()) == 0
                        && Integer.parseInt(playerA4.getText()) == 0 && Integer.parseInt(playerA5.getText()) == 0 && Integer.parseInt(playerA6.getText()) == 0) {
                    giliranPlayerB();
                }

                break;
            case 2:
                playerB6.setText(Integer.toString(isiB6 + 1));
                break;
            case 3:
                playerB5.setText(Integer.toString(isiB5 + 1));
                break;
            case 4:
                playerB4.setText(Integer.toString(isiB4 + 1));
                break;
            case 5:
                playerB3.setText(Integer.toString(isiB3 + 1));
                break;
            case 6:
                playerB2.setText(Integer.toString(isiB2 + 1));
                break;
            case 7:
                playerB1.setText(Integer.toString(isiB1 + 1));
                break;
            case 8:
                lumbungPlayerB.setText(Integer.toString(lumbungB + 1));
                if (Integer.parseInt(playerB1.getText()) == 0 && Integer.parseInt(playerB2.getText()) == 0 && Integer.parseInt(playerB3.getText()) == 0
                        && Integer.parseInt(playerB4.getText()) == 0 && Integer.parseInt(playerB5.getText()) == 0 && Integer.parseInt(playerB6.getText()) == 0) {
                    giliranPlayerA();
                }

                break;
            case 9:
                playerA6.setText(Integer.toString(isiA6 + 1));
                break;
            case 10:
                playerA5.setText(Integer.toString(isiA5 + 1));
                break;
            case 11:
                playerA4.setText(Integer.toString(isiA4 + 1));
                break;
            case 12:
                playerA3.setText(Integer.toString(isiA3 + 1));
                break;
            case 13:
                playerA2.setText(Integer.toString(isiA2 + 1));
                break;
            case 14:
                playerA1.setText(Integer.toString(isiA1 + 1));
                break;

        }   

    }

    private void playerA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerA1MouseClicked

        playerA = true;
        angka = Integer.parseInt(this.playerA1.getText());
        playerA1.setText("0");
        kasus = 14;
        run();
    }//GEN-LAST:event_playerA1MouseClicked

    private void playerA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerA2MouseClicked
        // TODO add your handling code here:

        playerA = true;
        angka = Integer.parseInt(this.playerA2.getText());
        playerA2.setText("0");
        kasus = 13;
        run();
    }//GEN-LAST:event_playerA2MouseClicked

    private void playerA3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerA3MouseClicked
        // TODO add your handling code here:
        playerA = true;
        angka = Integer.parseInt(this.playerA3.getText());
        playerA3.setText("0");
        kasus = 12;
        run();
    }//GEN-LAST:event_playerA3MouseClicked

    private void playerA4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerA4MouseClicked
        // TODO add your handling code here:
        playerA = true;
        angka = Integer.parseInt(this.playerA4.getText());
        playerA4.setText("0");
        kasus = 11;
        run();
    }//GEN-LAST:event_playerA4MouseClicked

    private void playerA5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerA5MouseClicked
        // TODO add your handling code here:
        playerA = true;
        angka = Integer.parseInt(this.playerA5.getText());
        playerA5.setText("0");
        kasus = 10;
        run();
    }//GEN-LAST:event_playerA5MouseClicked

    private void playerA6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerA6MouseClicked
        // TODO add your handling code here:
        playerA = true;
        angka = Integer.parseInt(this.playerA6.getText());
        playerA6.setText("0");
        kasus = 9;
        run();
    }//GEN-LAST:event_playerA6MouseClicked

    private void playerB6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerB6MouseClicked
        // TODO add your handling code here:
        playerA = false;
        angka = Integer.parseInt(this.playerB6.getText());
        playerB6.setText("0");
        kasus = 2;
        run();
    }//GEN-LAST:event_playerB6MouseClicked

    private void playerB5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerB5MouseClicked
        // TODO add your handling code here:

        playerA = false;
        angka = Integer.parseInt(this.playerB5.getText());
        playerB5.setText("0");
        kasus = 3;
        run();
    }//GEN-LAST:event_playerB5MouseClicked

    private void playerB4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerB4MouseClicked
        // TODO add your handling code here:
        playerA = false;
        angka = Integer.parseInt(this.playerB4.getText());
        playerB4.setText("0");
        kasus = 4;
        run();
    }//GEN-LAST:event_playerB4MouseClicked

    private void playerB3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerB3MouseClicked
        // TODO add your handling code here:
        playerA = false;
        angka = Integer.parseInt(this.playerB3.getText());
        playerB3.setText("0");
        kasus = 5;
        run();
    }//GEN-LAST:event_playerB3MouseClicked

    private void playerB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerB2MouseClicked
        // TODO add your handling code here:
        playerA = false;
        angka = Integer.parseInt(this.playerB2.getText());
        playerB2.setText("0");
        kasus = 6;
        run();
    }//GEN-LAST:event_playerB2MouseClicked

    private void playerB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerB1MouseClicked
        // TODO add your handling code here:
        playerA = false;
        angka = Integer.parseInt(this.playerB1.getText());
        playerB1.setText("0");
        kasus = 7;
        run();
    }//GEN-LAST:event_playerB1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dakonDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dakonDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dakonDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dakonDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dakonDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lumbungPlayerA;
    private javax.swing.JLabel lumbungPlayerB;
    private javax.swing.JLabel playerA1;
    private javax.swing.JLabel playerA2;
    private javax.swing.JLabel playerA3;
    private javax.swing.JLabel playerA4;
    private javax.swing.JLabel playerA5;
    private javax.swing.JLabel playerA6;
    private javax.swing.JLabel playerB1;
    private javax.swing.JLabel playerB2;
    private javax.swing.JLabel playerB3;
    private javax.swing.JLabel playerB4;
    private javax.swing.JLabel playerB5;
    private javax.swing.JLabel playerB6;
    private javax.swing.JLabel textPlayer;
    // End of variables declaration//GEN-END:variables
}
